#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - '**/etc/.*'
    - 'lib/*.js'
